### ISSUE TITLE
Consistent background color on pages

### ISSUE THREAD

**Issue by mtedeschi** [InteractiveMechanics/classicizing-philadelphia#6]
About and Events pages don't have a white background, but Get Involved does. Let's make that consistent and go with the white background.

**Comment by mtedeschi** [comment]
Also, on collections/browse, remove the white background here.

**Comment by cahdeemer** [comment]
What color background do you want on collections/browse?

**Comment by mtedeschi** [comment]
The normal background (the gray-ish beige color)

**Comment by cahdeemer** [comment]
Got it!
