### ISSUE TITLE
PHP error on collection/show page when you filter down

### ISSUE THREAD

**Issue by mtedeschi** [InteractiveMechanics/classicizing-philadelphia#7]
Notice: Undefined variable: item in /var/www/vhosts/interactivemechanics.com/staging/classphila/themes/classphila/collections/show.php on line 126

Let me know if you need me to look into this since its related to filtering.

**Comment by cahdeemer** [comment]
Line 126 didn't seem to be doing anything, so I just removed it.  And voila! The error vanished!

Just in case, though, this was line 126:
`<?php fire_plugin_hook('public_items_browse_each', array('view' => $this, 'item' =>$item)); ?>`
